version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - fullstack
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: "go-grpc-service"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    networks:
      - fullstack
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_TABLE: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_SSLMODE: "disable"

volumes:
  db_data:

networks:
  fullstack:
    driver: bridge